name: 14201Northwood
favicon: null
layout_spectrum: 0.87972
typography_spectrum: 0.58151
title: 14201 Northwood dr.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b3bbc6'
    - '#545e17'
    - '#8a99ac'
    - '#131c01'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.7949863448739052
purpose: []
