name: 14201Northwood
favicon: null
layout_spectrum: 0.6122675610240549
typography_spectrum: 0.06364419753663242
title: 14201 Northwood dr.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b3bbc6'
    - '#545e17'
    - '#8a99ac'
    - '#131c01'
  brandStrength: 0.40203172131441534
  lightness: 0.4978841708507389
  saturation: 0.86948601459153
  rhythmicContrast: 0.7949863448739052
purpose: []
